version: '3'

services: 

  app:
    build: 
      context: node
    image: patricmaffi/fullcycle-docker2
    container_name: app
    command: node index.js
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - node-network
    volumes: 
      - ./node/index.js:/usr/src/app/index.js
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: patricmaffi/nginx:prod
    container_name: nginx
    tty: true
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks: 
      - node-network
    ports: 
      - "8080:80"
      
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      
